// Using dwolla-v2 - https://github.com/Dwolla/dwolla-v2-node
var customerUrl =
  "https://api-sandbox.dwolla.com/customers/247B1BD8-F5A0-4B71-A898-F62F67B8AE1C";

dwolla
  .post(`${customerUrl}/card-funding-sources-token`)
  .then((res) => res.body.token); // => 'lr0Ax1zwIpeXXt8sJDiVXjPbwEeGO6QKFWBIaKvnFG0Sm2j7vL'
<head>
  <script src="https://cdn-b.dwolla.com/1/dwolla-cards.js"></script>
</head>
// Sandbox
dwolla.configure("sandbox");

// Production
dwolla.configure("prod");

// Sandbox
dwolla.configure("sandbox");

// Production
dwolla.configure("prod");


